package com.isc.model;
// Generated May 24, 2017 1:26:03 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Iclass generated by hbm2java
 */
@Entity
@Table(name = "iclass", catalog = "my_db")
public class Iclass implements java.io.Serializable {

	private Integer id;
	private Room room;
	private Subject subject;
	private Timetable timetable;
	private String iclassName;
	private int instructor;
	private Set<Time> times = new HashSet<Time>(0);

	public Iclass() {
	}

	public Iclass(Room room, Subject subject, Timetable timetable, String iclassName, int instructor) {
		this.room = room;
		this.subject = subject;
		this.timetable = timetable;
		this.iclassName = iclassName;
		this.instructor = instructor;
	}

	public Iclass(Room room, Subject subject, Timetable timetable, String iclassName, int instructor, Set<Time> times) {
		this.room = room;
		this.subject = subject;
		this.timetable = timetable;
		this.iclassName = iclassName;
		this.instructor = instructor;
		this.times = times;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room", nullable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject", nullable = false)
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "timetable", nullable = false)
	public Timetable getTimetable() {
		return this.timetable;
	}

	public void setTimetable(Timetable timetable) {
		this.timetable = timetable;
	}

	@Column(name = "iclass_name", nullable = false, length = 150)
	public String getIclassName() {
		return this.iclassName;
	}

	public void setIclassName(String iclassName) {
		this.iclassName = iclassName;
	}

	@Column(name = "instructor", nullable = false)
	public int getInstructor() {
		return this.instructor;
	}

	public void setInstructor(int instructor) {
		this.instructor = instructor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iclass")
	public Set<Time> getTimes() {
		return this.times;
	}

	public void setTimes(Set<Time> times) {
		this.times = times;
	}

}
