package com.isc.model;
// Generated Apr 15, 2017 8:46:24 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Intake generated by hbm2java
 */
@Entity
@Proxy(lazy =false)
@Table(name = "intake", catalog = "my_db", uniqueConstraints = @UniqueConstraint(columnNames = "intake_id"))
public class Intake implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String intakeId;
	private String intakeName;
	private Date startDate;
	private Date endDate;
	private boolean active;
	private Set<EntranceExam> entranceExams = new HashSet<EntranceExam>(0);
	private Set<Student> students = new HashSet<Student>(0);

	public Intake() {
	}

	public Intake(String intakeId, String intakeName, boolean active) {
		this.intakeId = intakeId;
		this.intakeName = intakeName;
		this.active = active;
	}

	public Intake(String intakeId, String intakeName, Date startDate, Date endDate, boolean active,
			Set<EntranceExam> entranceExams, Set<Student> students) {
		this.intakeId = intakeId;
		this.intakeName = intakeName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.active = active;
		this.entranceExams = entranceExams;
		this.students = students;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "intake_id", unique = true, nullable = false, length = 30)
	public String getIntakeId() {
		return this.intakeId;
	}

	public void setIntakeId(String intakeId) {
		this.intakeId = intakeId;
	}

	@Column(name = "intake_name", nullable = false, length = 30)
	public String getIntakeName() {
		return this.intakeName;
	}

	public void setIntakeName(String intakeName) {
		this.intakeName = intakeName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intake")
	public Set<EntranceExam> getEntranceExams() {
		return this.entranceExams;
	}

	public void setEntranceExams(Set<EntranceExam> entranceExams) {
		this.entranceExams = entranceExams;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intake")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
