package com.isc.model;
// Generated May 24, 2017 1:26:03 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * SessionDetail generated by hbm2java
 */
@Entity
@Table(name = "session_detail", catalog = "my_db")
@Proxy(lazy = false)
public class SessionDetail implements java.io.Serializable {

	private Integer id;
	private Session session;
	private Date timeStart;
	private Date timeEnd;
	private Set<Time> times = new HashSet<Time>(0);

	public SessionDetail() {
	}

	public SessionDetail(Session session, Date timeStart, Date timeEnd) {
		this.session = session;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
	}

	public SessionDetail(Session session, Date timeStart, Date timeEnd, Set<Time> times) {
		this.session = session;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.times = times;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "session", nullable = false)
	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time_start", nullable = false, length = 8)
	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time_end", nullable = false, length = 8)
	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "sessionDetail")
	public Set<Time> getTimes() {
		return this.times;
	}

	public void setTimes(Set<Time> times) {
		this.times = times;
	}

}
