package com.isc.model;

// default package
// Generated May 25, 2017 9:50:27 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Time generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "time", catalog = "my_db")
public class Time implements java.io.Serializable {

	private Integer id;
	private Iclass iclass;
	private Instructor instructor;
	private Room room;
	private SessionDetail sessionDetail;
	private Date date;

	public Time() {
	}

	public Time(Iclass iclass, SessionDetail sessionDetail, Date date) {
		this.iclass = iclass;
		this.sessionDetail = sessionDetail;
		this.date = date;
	}

	public Time(Iclass iclass, Instructor instructor, Room room, SessionDetail sessionDetail, Date date) {
		this.iclass = iclass;
		this.instructor = instructor;
		this.room = room;
		this.sessionDetail = sessionDetail;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iclass", nullable = false)
	public Iclass getIclass() {
		return this.iclass;
	}

	public void setIclass(Iclass iclass) {
		this.iclass = iclass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alt_instructor")
	public Instructor getInstructor() {
		return this.instructor;
	}

	public void setInstructor(Instructor instructor) {
		this.instructor = instructor;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alt_room")
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session_detail", nullable = false)
	public SessionDetail getSessionDetail() {
		return this.sessionDetail;
	}

	public void setSessionDetail(SessionDetail sessionDetail) {
		this.sessionDetail = sessionDetail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
