package com.isc.model;
// Generated May 24, 2017 1:26:03 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Time generated by hbm2java
 */
@Entity
@Table(name = "time", catalog = "my_db")
public class Time implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Iclass iclass;
	private Room room;
	private SessionDetail sessionDetail;
	private Date date;
	private Integer altInstructor;

	public Time() {
	}

	public Time(Iclass iclass, SessionDetail sessionDetail, Date date) {
		this.iclass = iclass;
		this.sessionDetail = sessionDetail;
		this.date = date;
	}

	public Time(Iclass iclass, Room room, SessionDetail sessionDetail, Date date, Integer altInstructor) {
		this.iclass = iclass;
		this.room = room;
		this.sessionDetail = sessionDetail;
		this.date = date;
		this.altInstructor = altInstructor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iclass", nullable = false)
	public Iclass getIclass() {
		return this.iclass;
	}

	public void setIclass(Iclass iclass) {
		this.iclass = iclass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alt_room")
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session_detail", nullable = false)
	public SessionDetail getSessionDetail() {
		return this.sessionDetail;
	}

	public void setSessionDetail(SessionDetail sessionDetail) {
		this.sessionDetail = sessionDetail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "alt_instructor")
	public Integer getAltInstructor() {
		return this.altInstructor;
	}

	public void setAltInstructor(Integer altInstructor) {
		this.altInstructor = altInstructor;
	}

}
