package com.isc.model;
// Generated May 24, 2017 1:26:03 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Timetable generated by hbm2java
 */
@Entity
@Table(name = "timetable", catalog = "my_db")
public class Timetable implements java.io.Serializable {

	private Integer id;
	private Session session;
	private String timetableName;
	private Integer intake;
	private Set<Iclass> iclasses = new HashSet<Iclass>(0);

	public Timetable() {
	}

	public Timetable(String timetableName) {
		this.timetableName = timetableName;
	}

	public Timetable(Session session, String timetableName, Integer intake, Set<Iclass> iclasses) {
		this.session = session;
		this.timetableName = timetableName;
		this.intake = intake;
		this.iclasses = iclasses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session")
	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	@Column(name = "timetable_name", nullable = false, length = 150)
	public String getTimetableName() {
		return this.timetableName;
	}

	public void setTimetableName(String timetableName) {
		this.timetableName = timetableName;
	}

	@Column(name = "intake")
	public Integer getIntake() {
		return this.intake;
	}

	public void setIntake(Integer intake) {
		this.intake = intake;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timetable")
	public Set<Iclass> getIclasses() {
		return this.iclasses;
	}

	public void setIclasses(Set<Iclass> iclasses) {
		this.iclasses = iclasses;
	}

}
